server.port=8080
spring.jpa.properties.hibernate.format_sql=true
security.jwt.secret-key=e69fdb95e470aa4ff82d628bc25e7a37af9598c3c48f03bfba0ab71a94780970
security.jwt.expiration-time=86400000
security.jwt.refresh-time= 604800000
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devenderdalal8@gmail.com
spring.mail.password=apqk nzcn ajhy nsif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.profiles.default=Development
# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

#spring.profiles.active=mysql
spring.profiles.active=mysql

logging.level.org.springframework.web=INFO
logging.level.com.carpool=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always